---
- name: My first play
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Display system information
      ansible.builtin.command: uname -a
      register: system_info

    - name: Show system info
      ansible.builtin.debug:
        var: system_info.stdout